version: '3'
services:
  fullstackapplication:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=postgres
    networks:
      - mynetwork


  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  mynetwork:
